USE master
GO
IF DB_ID('FOODAHOLIC_MANAGEMENT') IS NOT NULL
	DROP DATABASE FOODAHOLIC_MANAGEMENT
GO
CREATE DATABASE FOODAHOLIC_MANAGEMENT
GO
USE FOODAHOLIC_MANAGEMENT
GO

CREATE TABLE ACCOUNT
(
	USERNAME VARCHAR(20),
	PASSWORD VARCHAR(20),
	FIRSTNAME NVARCHAR(30),
	SURNAME NVARCHAR(30),
	GENDER VARCHAR(6) CHECK (GENDER IN (NULL, 'MALE', 'FEMALE')),
	ADDRESS NVARCHAR(100),
	EMAIL VARCHAR(100),
	PHONENUMBER VARCHAR(12),
	DATEOFBIRTH DATE,
	AVATAR IMAGE,
	COVER IMAGE,
	ACCOUNTTYPE VARCHAR(5) CHECK (ACCOUNTTYPE IN ('USER', 'ADMIN')),
	CREATEDTIME DATETIME,
	STATUS VARCHAR(7) CHECK (STATUS IN ('ONLINE', 'OFFLINE')),
	AVAILABLE BIT,
	ENDOFSUSPENDTIME DATETIME

	CONSTRAINT PK_ACCOUNT
	PRIMARY KEY(USERNAME)
)

CREATE TABLE FOLLOW
(
	ID INT,
	STARTUSER VARCHAR(20),
	ENDUSER VARCHAR(20)

	CONSTRAINT PK_FOLLOW
	PRIMARY KEY(ID)
)

CREATE TABLE MY_FAVORITE
(
	ID INT,
	STARTUSER VARCHAR(20),
	POSTID INT,
	CREATEDTIME DATETIME

	CONSTRAINT PK_FAVORITE
	PRIMARY KEY(ID)
)

CREATE TABLE USERNOTIFICATION
(
	ID INT,
	ENDUSER VARCHAR(20),
	CREATEDTIME DATETIME,
	CONTENT NVARCHAR(500)

	CONSTRAINT PK_USERNOTI
	PRIMARY KEY(ID)
)

CREATE TABLE REPORTED_POST
(
	ID INT,
	POSTID INT,
	REPORTINGUSER VARCHAR(20),
	REPORTINGTIME DATETIME,
	REASON_TEXT NVARCHAR(500),

	CONSTRAINT PK_REPORTEDPOST
	PRIMARY KEY(ID)
)

CREATE TABLE REPORTED_COMMENT
(
	ID INT,
	COMMENTID INT,
	REPORTINGUSER VARCHAR(20),
	REPORTINGTIME DATETIME,
	REASON_TEXT NVARCHAR(500),

	CONSTRAINT PK_REPORTEDCOMMENT
	PRIMARY KEY(ID)
)

CREATE TABLE STEPS_TO_COOK
(
	POSTID INT,
	STEPORDER INT,
	DETAILEDSTEP NVARCHAR(500),

	CONSTRAINT PK_STC
	PRIMARY KEY(POSTID, STEPORDER)
)

CREATE TABLE POST
(
	ID INT,
	POSTINGUSER VARCHAR(20),
	POSTINGTIME DATETIME,
	RECIPENAME NVARCHAR(100),
	PREPARATIONTIME VARCHAR(20),
	COOKINGTIME VARCHAR(20),
	THUMBNAIL IMAGE,
	SHORT_DESCRIPTION NVARCHAR(500),
	AVAILABLE BIT

	CONSTRAINT PK_POST
	PRIMARY KEY(ID)
)

CREATE TABLE POST_IMAGES 
(
	POST_ID INT,
	IMAGE_ORDER INT,
	POST_IMAGE IMAGE

	CONSTRAINT PK_ID
	PRIMARY KEY(POST_ID, IMAGE_ORDER)
)

CREATE TABLE LIKEPOST
(
	ID INT,
	STARTUSER VARCHAR(20),
	POSTID INT,
	LIKETIME DATETIME,
	TYPEOFLIKE VARCHAR(5) CHECK (TYPEOFLIKE IN ('Love', 'Haha', 'Angry', NULL))

	CONSTRAINT PK_LIKEPOST
	PRIMARY KEY(ID)
)

CREATE TABLE REPORTED_ACCOUNT
(
	ID INT,
	REPORTINGUSER VARCHAR(20),
	REPORTINGTIME DATETIME,
	ENDUSER VARCHAR(20),
	REASON_TEXT NVARCHAR(500),

	CONSTRAINT PK_REPORTEDACCOUNT
	PRIMARY KEY(ID)
)

CREATE TABLE INGREDIENTS
(
	POSTID INT,
	INGREDIENTID INT,
	INGREDIENT_STRING NVARCHAR(500),

	CONSTRAINT PK_FOOD
	PRIMARY KEY(POSTID, INGREDIENTID)
)

CREATE TABLE COMMENT
(
	ID INT,
	STARTUSER VARCHAR(20),
	POSTID INT,
	COMMENTINGTIME DATETIME,
	CONTENT NVARCHAR(500),
	AVAILABLE BIT

	CONSTRAINT PK_COMMENT
	PRIMARY KEY(ID)
)

CREATE TABLE CALORIES
(
	POSTID INT,
	AMOUNT INT

	CONSTRAINT PK_CALORIES
	PRIMARY KEY(POSTID)
)
CREATE TABLE AVERAGE_NUTRITION
(
	POSTID INT,
	NUTRITIONID INT,
	NUTRITION_STRING NVARCHAR(500),

	CONSTRAINT PK_AVERAGENUTRITION
	PRIMARY KEY(POSTID, NUTRITIONID)
)

ALTER TABLE CALORIES
ADD 
	CONSTRAINT FK_CALORIES_POST
	FOREIGN KEY(POSTID)
	REFERENCES POST

ALTER TABLE FOLLOW
ADD
	CONSTRAINT FK_FOLLOW_ACCOUNT_STARTUSER
	FOREIGN KEY(STARTUSER)
	REFERENCES ACCOUNT,
	CONSTRAINT FK_FOLLOW_ACCOUNT_ENDUSER
	FOREIGN KEY(ENDUSER)
	REFERENCES ACCOUNT

ALTER TABLE MY_FAVORITE
ADD
	CONSTRAINT FK_FAVORITE_ACCOUNT
	FOREIGN KEY(STARTUSER)
	REFERENCES ACCOUNT,
	CONSTRAINT FK_FAVORITE_POST
	FOREIGN KEY(POSTID)
	REFERENCES POST

ALTER TABLE USERNOTIFICATION
ADD
	CONSTRAINT FK_NOTI_ACCOUNT
	FOREIGN KEY(ENDUSER)
	REFERENCES ACCOUNT

ALTER TABLE REPORTED_POST
ADD
	CONSTRAINT FK_RP_ACCOUNT
	FOREIGN KEY(REPORTINGUSER)
	REFERENCES ACCOUNT,
	CONSTRAINT FK_RP_POST
	FOREIGN KEY(POSTID)
	REFERENCES POST

ALTER TABLE REPORTED_COMMENT
ADD
	CONSTRAINT FK_RC_ACCOUNT
	FOREIGN KEY(REPORTINGUSER)
	REFERENCES ACCOUNT,
	CONSTRAINT FK_RC_COMMENT
	FOREIGN KEY(COMMENTID)
	REFERENCES COMMENT

ALTER TABLE REPORTED_ACCOUNT
ADD
	CONSTRAINT FK_RA_ACCOUNT_REPORTINGUSER
	FOREIGN KEY(REPORTINGUSER)
	REFERENCES ACCOUNT,
	CONSTRAINT FK_RA_ACCOUNT_ENDUSER
	FOREIGN KEY(ENDUSER)
	REFERENCES ACCOUNT

ALTER TABLE STEPS_TO_COOK
ADD
	CONSTRAINT FK_STC_POST
	FOREIGN KEY(POSTID)
	REFERENCES POST

ALTER TABLE POST
ADD
	CONSTRAINT FK_POST_ACCOUNT
	FOREIGN KEY(POSTINGUSER)
	REFERENCES ACCOUNT

ALTER TABLE POST_IMAGES
ADD
	CONSTRAINT FK_POSTIMAGES_POST
	FOREIGN KEY(POST_ID)
	REFERENCES POST

ALTER TABLE LIKEPOST
ADD
	CONSTRAINT FK_LIKE_ACCOUNT
	FOREIGN KEY(STARTUSER)
	REFERENCES ACCOUNT,
	CONSTRAINT FK_LIKE_POST
	FOREIGN KEY(POSTID)
	REFERENCES POST

ALTER TABLE COMMENT
ADD
	CONSTRAINT FK_COMMENT_POST
	FOREIGN KEY(POSTID)
	REFERENCES POST

ALTER TABLE INGREDIENTS
ADD
	CONSTRAINT FK_INGREDIENTS_POST
	FOREIGN KEY(POSTID)
	REFERENCES POST

ALTER TABLE AVERAGE_NUTRITION
ADD
	CONSTRAINT FK_AVERAGE_NUTRITION_POST
	FOREIGN KEY(POSTID)
	REFERENCES POST

--INSERT ACCOUNT
--VALUES('ngthiennhan2002', 'ngthiennhan2002', N'Nhân', N'Nguyễn Thiện', 'TPHCM', 'ngthiennhan2002@gmail.com', '0934058891', '2002-03-15', (SELECT * FROM OPENROWSET(BULK N'D:\test.png', SINGLE_BLOB) as AVA), NULL, 'USER', GETDATE(), 'OFFLINE', 1, NULL)

INSERT ACCOUNT
VALUES('GUEST', 'GUEST', N'GUEST', N'GUEST', NULL, NULL, NULL, NULL, NULL, (SELECT * FROM OPENROWSET(BULK N'C:\Users\ngthi\OneDrive\Máy tính\NMCNPM\Thực hành\Đồ án\Coding\Images\anonymous_avatar.png', SINGLE_BLOB) as AVATAR), (SELECT * FROM OPENROWSET(BULK N'C:\Users\ngthi\OneDrive\Máy tính\NMCNPM\Thực hành\Đồ án\Coding\Images\default_cover.jpg', SINGLE_BLOB) as COVER), 'USER', NULL, NULL, 1, NULL)


SELECT * FROM ACCOUNT
SELECT * FROM POST
SELECT * FROM POST_IMAGES
SELECT * FROM STEPS_TO_COOK
SELECT * FROM INGREDIENTS
SELECT * FROM CALORIES
SELECT * FROM AVERAGE_NUTRITION
SELECT * FROM LIKEPOST
SELECT * FROM REPORTED_POST
SELECT * FROM MY_FAVORITE

SELECT STARTUSER, POSTID FROM MY_FAVORITE WHERE POSTID = '1000' AND STARTUSER = 'ngthiennhan2002'

SELECT P.ID, ACC.AVATAR, P.POSTINGUSER, P.THUMBNAIL, P.POSTINGTIME
FROM POST P, ACCOUNT ACC
WHERE P.POSTINGUSER = ACC.USERNAME
AND P.AVAILABLE = 1
ORDER BY P.POSTINGTIME DESC


DECLARE @POSTID INT
SET @POSTID = 1000
--GET POST AND USERNAME--
SELECT P.ID, P.POSTINGUSER, ACC.FIRSTNAME + ' ' + ACC.SURNAME AS FULLNAME, ACC.AVATAR, P.RECIPENAME, P.PREPARATIONTIME, P.COOKINGTIME, P.THUMBNAIL, P.SHORT_DESCRIPTION
FROM POST P, ACCOUNT ACC
WHERE P.AVAILABLE = 1
AND P.POSTINGUSER = ACC.USERNAME
AND P.ID = @POSTID


DECLARE @RECIPENAME NVARCHAR(500)
SET @RECIPENAME = N'cơm'
--GET POST AND USERNAME BY RECIPE NAME--
SELECT P.ID, P.POSTINGUSER, ACC.AVATAR, P.RECIPENAME, P.THUMBNAIL, CALO.AMOUNT
FROM POST P, ACCOUNT ACC, CALORIES CALO
WHERE P.AVAILABLE = 1
AND P.POSTINGUSER = ACC.USERNAME
AND P.ID = CALO.POSTID
AND CHARINDEX(@RECIPENAME, P.RECIPENAME) > 0

DECLARE @INGREDIENT NVARCHAR(500)
SET @INGREDIENT = N'SỮA'
--GET POST AND USERNAME BY INGREDIENT--
SELECT DISTINCT P.ID, P.POSTINGUSER, P.RECIPENAME, CALO.AMOUNT
FROM POST P, INGREDIENTS ING, ACCOUNT ACC, CALORIES CALO
WHERE P.AVAILABLE = 1
AND P.POSTINGUSER = ACC.USERNAME
AND P.ID = CALO.POSTID
AND P.ID = ING.POSTID
AND CHARINDEX(@INGREDIENT, ING.INGREDIENT_STRING) > 0

SELECT ACC.AVATAR, P.THUMBNAIL
FROM POST P, ACCOUNT ACC
WHERE P.POSTINGUSER = ACC.USERNAME
AND P.ID = 1006

DECLARE @POSTID INT
SET @POSTID = 1000
--GET INGREDIENTS--
SELECT ING.INGREDIENT_STRING
FROM INGREDIENTS ING, POST P
WHERE P.ID = ING.POSTID
AND P.ID = @POSTID


DECLARE @POSTID INT
SET @POSTID = 1000
--GET STEPS--
SELECT STEPS.DETAILEDSTEP
FROM STEPS_TO_COOK STEPS, POST P
WHERE P.ID = STEPS.POSTID
AND P.ID = @POSTID


DECLARE @POSTID INT
SET @POSTID = 1000
--GET CALORIES--
SELECT CALO.AMOUNT
FROM CALORIES CALO, POST P
WHERE P.ID = CALO.POSTID
AND P.ID = @POSTID


DECLARE @POSTID INT
SET @POSTID = 1000
--GET ADDITIONAL NUTRITION--
SELECT AVENU.NUTRITION_STRING
FROM AVERAGE_NUTRITION AVENU, POST P
WHERE P.ID = AVENU.POSTID
AND P.ID = @POSTID

DECLARE @POSTID INT
SET @POSTID = 1000
--GET ADDITIONAL IMAGES--
SELECT PIMG.POST_IMAGE
FROM POST_IMAGES PIMG, POST P
WHERE P.ID = PIMG.POST_ID
AND P.ID = @POSTID


DECLARE @POSTID INT
SET @POSTID = 1000
--GET LIKE--
SELECT LIKEP.TYPEOFLIKE, COUNT(*) AS NUMBER
FROM LIKEPOST LIKEP, POST P
WHERE P.ID = LIKEP.POSTID
AND P.ID = @POSTID
AND LIKEP.TYPEOFLIKE != 'NULL'
GROUP BY LIKEP.TYPEOFLIKE
ORDER BY COUNT(*) DESC

UPDATE LIKEPOST SET TYPEOFLIKE = 'NULL' WHERE POSTID = '1005' AND STARTUSER = 'ngthiennhan2002'

DECLARE @POSTID INT
DECLARE @USERNAME VARCHAR(20)
SET @POSTID = 1000
SET @USERNAME = 'ngthiennhan2002'
--GET MY LIKE--
SELECT LIKEP.STARTUSER, LIKEP.TYPEOFLIKE
FROM LIKEPOST LIKEP, POST P
WHERE LIKEP.POSTID = P.ID
AND P.ID = @POSTID
AND LIKEP.STARTUSER = @USERNAME
AND LIKEP.TYPEOFLIKE != 'NULL'

DECLARE @POSTID INT
DECLARE @USERNAME VARCHAR(20)
SET @POSTID = 1000
SET @USERNAME = 'ngthiennhan2002'
--GET MY FAVORITE--
SELECT FAV.*
FROM MY_FAVORITE FAV, POST P
WHERE P.ID = FAV.POSTID
AND P.ID = @POSTID
AND FAV.STARTUSER = @USERNAME

DECLARE @POSTID INT
SET @POSTID = 1000
--GET COMMENTS--
SELECT CMT.ID, CMT.STARTUSER, CMT.CONTENT, ACC.AVATAR
FROM COMMENT CMT, POST P, ACCOUNT ACC
WHERE P.ID = CMT.POSTID
AND P.ID = @POSTID
AND P.AVAILABLE = 1
AND ACC.USERNAME = CMT.STARTUSER